// Example output generated by Babel ES -> CommonJS transpilation
Object.defineProperty(exports, "__esModule", { value: true });

function hello() {
    console.log('hello');
}

exports.default = hello;
